apiVersion: v1
description: File, Block, and Object Storage Services for your Cloud-Native Environment
name: rook-nfs
version: 0.1.0
icon: https://rook.io/images/rook-logo.svg
sources:
  - https://github.com/rook/rook
